server:
  port: 9007
spring:
  application:
    name: agent-system
  cloud:
    nacos:
      discovery: { server-addr: localhost:8848 }
      config:   { server-addr: localhost:8848, file-extension: yaml }
